@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{azurehost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "nnhaodev14102000@gmail.com",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot
GET {{baseUrl}}/api/mas/v1/slots
?isIn=false
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a slot
GET {{baseUrl}}/api/mas/v1/slots/f540f061-8a86-4ef7-a551-b8a1b952975e
Content-Type: {{contentType}}
Authorization: {{authToken}}
###

# Create Appointment
POST {{baseUrl}}/api/mas/v1/appointments
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "slotId": "f540f061-8a86-4ef7-a551-b8a1b952975e",
  "briefProblem": "Em ko bit phan tich la gì...."
}

###

# Get own appointment
GET {{baseUrl}}/api/mas/v1/users/send/appointments
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get own appointment
GET {{baseUrl}}/api/mas/v1/users/send/appointments/cb05a6ef-03dc-4bc9-8d64-1b76b382062c
Content-Type: {{contentType}}
Authorization: {{authToken}}

###