@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{host}}
@contentType = application/json
@token = {{loginAdmin.response.body.$.message}}
@authToken = bearer {{token}}


# @name loginAdmin
POST {{baseUrl}}/api/mas/v1/accounts/login-admin
content-type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "Pa55w0rd!"
}

###

# Send mail
POST {{baseUrl}}/api/mas/v1/email/send
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "toEmail": "nnhao9a3@gmail.com",
  "subject": "Test email",
  "body": "Test email"
}