@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{azurehost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "MinhMentor@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Update user profile
PUT {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Mento 01",
  "avatar": "xxx.xxx.xxx.xxx",
  "introduce": "Nice to help you!",
  "meetUrl": "yyy.yyy.yyy.yyy"
}

###

# Get all subject
GET {{baseUrl}}/api/mas/v1/subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get mentor subject 
GET {{baseUrl}}/api/mas/v1/mentor-subjects/8face6ee-16a7-4f66-9277-53637e428715
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Register mentor subject
POST {{baseUrl}}/api/mas/v1/mentor-subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "subjectId": "fbf78f2f-30d8-4426-a0c0-574d636b34b6",
  "briefInfo": "5 years experience in tech this in FPT University",
}

###

# Update mentor subject
PUT {{baseUrl}}/api/mas/v1/mentor-subjects/8c1deffe-0e23-4637-ab55-7a51080aebdc
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "briefInfo": "Know test everythings, backend, fontend, have family with many testing tool, 10 years experience in tester, QA, QC"
}

###