@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{lchost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "user@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get mentor subject 
GET {{baseUrl}}/api/mas/v1/mentor-subjects/aaf445eb-c5c6-4a7e-8ae4-d15f40cd1df9
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all subject
GET {{baseUrl}}/api/mas/v1/subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Register mentor subject
POST {{baseUrl}}/api/mas/v1/mentor-subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "subjectId": "046cfc17-cec6-4725-b12a-b04b99dccd1f",
  "briefInfo": "Biết  test đủ thứ..."
}

###

# Update mentor subject
PUT {{baseUrl}}/api/mas/v1/mentor-subjects/8993ac7d-7ac1-4b9e-856d-45fe75a0333a
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "briefInfo": "Know test everythings, backend, fontend, have family with many testing tool, 10 years experience in tester, QA, QC"
}

###