@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{lchost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "testMentor01@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Update user profile
PUT {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "name": "Mento 01",
  "avatar": "xxx.xxx.xxx.xxx",
  "introduce": "Nice to help you!",
  "meetUrl": "yyy.yyy.yyy.yyy"
}

###

# Get all subject
GET {{baseUrl}}/api/mas/v1/subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get mentor subject 
GET {{baseUrl}}/api/mas/v1/mentor-subjects/a3ef5dc6-5ddd-4467-ab71-f4fa2242997f
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Register mentor subject
POST {{baseUrl}}/api/mas/v1/mentor-subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "subjectId": "637a18c2-4323-4d43-9791-98577fa65d60",
  "briefInfo": "Help you know how to dev a true project, and how to make a good team",
}

###

# Update mentor subject
PUT {{baseUrl}}/api/mas/v1/mentor-subjects/8c1deffe-0e23-4637-ab55-7a51080aebdc
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "briefInfo": "Know test everythings, backend, fontend, have family with many testing tool, 10 years experience in tester, QA, QC"
}

###