@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{lchost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "testMentor01@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot of mentor 02
GET {{baseUrl}}/api/mas/v1/slots
?mentorId=
&from=2022-07-03T07:23:58.277
&to=2022-07-05T07:23:58.277
&isAsc=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot of mentor 01
GET {{baseUrl}}/api/mas/v1/slots
?mentorId=
&isAsc=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all subjects
GET {{baseUrl}}/api/mas/v1/subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a subject
GET {{baseUrl}}/api/mas/v1/subjects/4248deaa-294c-4637-85fb-eebfd578ee5f
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Create slot
POST {{baseUrl}}/api/mas/v1/slots
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "startTime": "2022-07-19T07:23:58.276Z",
  "finishTime": "2022-07-19T08:23:58.276Z",
  "slotSubjects": [
    {
      "subjectId": "637a18c2-4323-4d43-9791-98577fa65d60",
      "description": "Sample project with me v9"
    }
  ]
}

###

# Get a slot by Id
GET {{baseUrl}}/api/mas/v1/slots/032c1774-8a9e-4a79-8e61-84f3eb3f7f99
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Delete a slot
DELETE {{baseUrl}}/api/mas/v1/slots/032c1774-8a9e-4a79-8e61-84f3eb3f7f99
Content-Type: {{contentType}}
Authorization: {{authToken}}

###