@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{azurehost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "MinhMentor@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot of mentor 02
GET {{baseUrl}}/api/mas/v1/slots
?mentorId=
&from=
&to=
&isAsc=false
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot of mentor 01
GET {{baseUrl}}/api/mas/v1/slots
?mentorId=
&isAsc=true
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all subjects
GET {{baseUrl}}/api/mas/v1/subjects
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get a subject
GET {{baseUrl}}/api/mas/v1/subjects/4248deaa-294c-4637-85fb-eebfd578ee5f
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Create slot
POST {{baseUrl}}/api/mas/v1/slots
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "startTime": "2022-07-13T07:00:58.276Z",
  "finishTime": "2022-07-13T09:30:58.276Z",
  "slotSubjects": [
    {
      "subjectId": "1cf02e08-a7ff-433a-8787-0ce0e8dc36e6",
      "description": "ÔN thi toán rời rạc 1"
    }
  ]
}

###

# Get a slot by Id
GET {{baseUrl}}/api/mas/v1/slots/f540f061-8a86-4ef7-a551-b8a1b952975e
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Delete a slot
DELETE {{baseUrl}}/api/mas/v1/slots/032c1774-8a9e-4a79-8e61-84f3eb3f7f99
Content-Type: {{contentType}}
Authorization: {{authToken}}

###