@hostname = localhost
@port = 5001
@azurehost = mas-api.azurewebsites.net
@lchost = {{hostname}}:{{port}}
@host = {{azurehost}}
@baseUrl = https://{{lchost}}
@contentType = application/json
@token = {{login.response.body.$.message}}
@authToken = bearer {{token}}

# @name login
POST {{baseUrl}}/api/mas/v1/accounts/login-user
content-type: {{contentType}}

{
  "email": "user@fe.edu.vn",
  "password": "Pa55w0rd!"
}
###

# Get user profile
GET {{baseUrl}}/api/mas/v1/users/personal
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Get all slot
GET {{baseUrl}}/api/mas/v1/slots
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Create slot
POST {{baseUrl}}/api/mas/v1/slots
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
  "startTime": "2022-06-25T15:00:02.989Z",
  "finishTime": "2022-06-25T16:00:02.989Z"
}

###

# Get a slot by Id
GET {{baseUrl}}/api/mas/v1/slots/032c1774-8a9e-4a79-8e61-84f3eb3f7f99
Content-Type: {{contentType}}
Authorization: {{authToken}}

###

# Delete a slot
DELETE {{baseUrl}}/api/mas/v1/slots/032c1774-8a9e-4a79-8e61-84f3eb3f7f99
Content-Type: {{contentType}}
Authorization: {{authToken}}

###